[colors]
[colors.primary]
background = "#1F1F1F"
foreground = "#ffffff"

[colors.normal]
black   = "#1F1F1F"
red     = "#F44336"
green   = "#e75a50"
yellow  = "#a99b7a"
blue    = "#6d6d6d"
magenta = "#b6b6b6"
cyan    = "#99a4af"
white   = "#ffffff"

[colors.bright]
black   = "#929292"
red     = "#f44336"
green   = "#e75a50"
yellow  = "#a99b7a"
blue    = "#6d6d6d"
magenta = "#b6b6b6"
cyan    = "#99a4af"
white   = "#ffffff"

[colors.cursor]
text   = "#1F1F1F"
cursor = "#ffffff"
