accent = "#6d6d6d"
cursor = "#e75a50"
foreground = "#efebdc"
background = "#1F1F1F"
selection_foreground = "#1F1F1F"
selection_background = "#e75a50"

color0 = "#1F1F1F"
color1 = "#F44336"
color2 = "#e75a50"
color3 = "#a99b7a"
color4 = "#6d6d6d"
color5 = "#77838a"
color6 = "#b6b6b6"
color7 = "#efebdc"
color8 = "#929292"
color9 = "#f44336"
color10 = "#e75a50"
color11 = "#a99b7a"
color12 = "#6d6d6d"
color13 = "#77838a"
color14 = "#b6b6b6"
color15 = "#efebdc"
