
# ========= Border =========
file_panel_border = '#E1CE98'
sidebar_border = '#E1CE98'
footer_border = '#E1CE98'

# ========= Border Active =========
file_panel_border_active = '#e58980'
sidebar_border_active = '#e58980'
footer_border_active = '#e58980'
modal_border_active = '#e58980'

# ========= Background (bg) =========
full_screen_bg = '#1F1F1F'
file_panel_bg = '#1F1F1F'
sidebar_bg = '#1F1F1F'
footer_bg = '#1F1F1F'
modal_bg = '#1F1F1F'

# ========= Foreground (fg) =========
full_screen_fg = '#efebdc'
file_panel_fg = '#efebdc'
sidebar_fg = '#efebdc'
footer_fg = '#efebdc'
modal_fg = '#efebdc'

# ========= Special Color =========
cursor = '#efebdc'
correct = '#e75a50'
error = '#F44336'
hint = '#6d6d6d'
cancel = '#F44336'
gradient_color = ['#1F1F1F', "#929292"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#1F1F1F'
file_panel_top_path = '#929292'
file_panel_item_selected_fg = '#929292'
file_panel_item_selected_bg = '#1F1F1F'

# ========= Sidebar Special Items =========
sidebar_title = '#efebdc'
sidebar_item_selected_fg = '#929292'
sidebar_item_selected_bg = '#1F1F1F'
sidebar_divider = '#E1CE98'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#F44336'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#e75a50'
