
# ========= Border =========
file_panel_border = '#e6efff'
sidebar_border = '#e6efff'
footer_border = '#e6efff'

# ========= Border Active =========
file_panel_border_active = '#8484a0'
sidebar_border_active = '#8484a0'
footer_border_active = '#8484a0'
modal_border_active = '#8484a0'

# ========= Background (bg) =========
full_screen_bg = '#1F1F1F'
file_panel_bg = '#1F1F1F'
sidebar_bg = '#1F1F1F'
footer_bg = '#1F1F1F'
modal_bg = '#1F1F1F'

# ========= Foreground (fg) =========
full_screen_fg = '#e6efff'
file_panel_fg = '#e6efff'
sidebar_fg = '#e6efff'
footer_fg = '#e6efff'
modal_fg = '#e6efff'

# ========= Special Color =========
cursor = '#e6efff'
correct = '#e75a50'
error = '#F44336'
hint = '#99a4af'
cancel = '#F44336'
gradient_color = ['#1F1F1F', "#929292"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#1F1F1F'
file_panel_top_path = '#929292'
file_panel_item_selected_fg = '#929292'
file_panel_item_selected_bg = '#1F1F1F'

# ========= Sidebar Special Items =========
sidebar_title = '#e6efff'
sidebar_item_selected_fg = '#929292'
sidebar_item_selected_bg = '#1F1F1F'
sidebar_divider = '#e6efff'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#F44336'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#e75a50'
